### ISSUE TITLE
Text not filling automatically in all field

### ISSUE THREAD

**Issue by Elamuruga** [ehsanomid/OTPTextView#1]
While performing copy and paste of OTP number. It's not filling automatically to all fields. All copied OTP numbers were filled in the single field alone. Could you help me with this?

**Comment by ehsanomid** [comment]
good point! I should add this feature! I will add it soon. just keep an eye on it. thanks

**Comment by ehsanomid** [comment]
I've added clipboard feature

**Comment by Elamuruga** [comment]
> I've added clipboard feature

Hi thanks for immediate response.. And one more doubt did you start support text content type? Auto fill otp method?

**Comment by ehsanomid** [comment]
I've added a new a mthod called getFromClipBoardAndFill() , it automatically fill the textes, the number of digits and OTP must be the same.

**Comment by Elamuruga** [comment]
> I've added a new a mthod called getFromClipBoardAndFill() , it automatically fill the textes, the number of digits and OTP must be the same.
Superb... Thank u lot.. give me your mail id i validate all the scenarios and if i find any bug i sent you recorded video.. That will be help to you.

**Comment by Elamuruga** [comment]
Superb... Thank u lot.. give me your mail id i validate all the scenarios and if i find any bug i sent you recorded video.. That will be help to you.
