### ISSUE TITLE
Not Supporting RTL

### ISSUE THREAD

**Issue by Elamuruga** [ehsanomid/OTPTextView#2]
While user language has changed to LTR to RTL. Textfield container was still in the LTR format.

**Comment by ehsanomid** [comment]
do we have any language which numbers are written from Right to left?

**Comment by Elamuruga** [comment]
> do we have any language which numbers are written from Right to left?

Ya off course generally arabic and urdu users were written in right to left only.. numbers, name what ever it is uitextfield and total view should be in Right to left semantic content attribute only..

**Comment by ehsanomid** [comment]
even for numbers?

**Comment by Elamuruga** [comment]
> even for numbers?

Ya number also needed their writing pattern right to left while RTL cursor and indicator should begins from right side..its ok i did it now.. no problem man.. i close this issue. cool☺️
